# Generated by Django 5.1.3 on 2024-11-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_category_post_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
