# Generated by Django 5.1.3 on 2024-12-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_remove_comment_name_comment_author_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
