# Generated by Django 5.1.3 on 2024-12-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
