# Generated by Django 5.1.3 on 2025-01-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='created_at',
        ),
    ]
